import { FundDetails } from './types';

const navHistorySample = Array.from({ length: 30 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (30 - i));
  return {
    date: date.toISOString().split('T')[0],
    nav: 100 + i * Math.sin(i / 2) * 5 + Math.random() * 5,
  };
});

export const fundData: Record<string, FundDetails> = {
  'nippon-india-large-cap-fund': {
    name: 'Nippon India Large Cap Fund',
    slug: 'nippon-india-large-cap-fund',
    aum: '₹25,678 Cr',
    manager: 'Shailesh Raj Bhan',
    investmentStrategy: {
      overview:
        'The fund primarily invests in large-cap stocks, aiming for long-term capital appreciation by picking companies with sustainable growth potential and strong management.',
      oneYearReturn: '28.5%',
      threeYearReturn: '15.2%',
      fiveYearReturn: '17.8%',
    },
    navHistory: navHistorySample.map(d => ({ ...d, nav: d.nav * 1.2 })),
    holdings: [
      { company: 'HDFC Bank Ltd.', percentage: 9.8 },
      { company: 'ICICI Bank Ltd.', percentage: 8.5 },
      { company: 'Infosys Ltd.', percentage: 7.2 },
      { company: 'Reliance Industries Ltd.', percentage: 6.5 },
      { company: 'Tata Consultancy Services Ltd.', percentage: 5.1 },
    ],
    performanceMetrics: [
      { metric: 'Alpha', value: '2.1%', average: '1.5%' },
      { metric: 'Beta', value: '0.95', average: '1.0' },
      { metric: 'Standard Deviation', value: '18.5%', average: '19.2%' },
      { metric: 'Sharpe Ratio', value: '0.8', average: '0.7' },
    ],
    peerComparison: [
        { fundName: 'HDFC Top 100', peRatio: '26.1', beta: 0.98, sharpeRatio: 0.75, upsideRatio: 85, downsideRatio: 90 },
        { fundName: 'ICICI Pru Bluechip', peRatio: '27.5', beta: 0.96, sharpeRatio: 0.82, upsideRatio: 90, downsideRatio: 88 },
        { fundName: 'SBI BlueChip Fund', peRatio: '25.9', beta: 0.94, sharpeRatio: 0.78, upsideRatio: 88, downsideRatio: 85 },
    ],
    assetAllocation: [
      { name: 'Equity', value: 95, fill: 'var(--color-chart-1)' },
      { name: 'Debt', value: 3, fill: 'var(--color-chart-2)' },
      { name: 'Cash', value: 2, fill: 'var(--color-chart-3)' },
    ],
    portfolioChanges: {
      sectorShifts: 'Increased allocation to financial services and reduced exposure to IT in the last quarter.',
      regulations: 'Fully compliant with SEBI regulations on large-cap fund allocations.',
      exitLoad: '1% for redemption within 1 year.',
    },
    strategicPositioning: 'Positioned to capture growth in top Indian companies, with a focus on stable earnings and market leadership.',
  },
  'hdfc-gold-fund': {
    name: 'HDFC Gold Fund',
    slug: 'hdfc-gold-fund',
    aum: '₹9,876 Cr',
    manager: 'Priya Sharma',
    investmentStrategy: {
      overview: 'This fund invests in physical gold and gold-related instruments, serving as a hedge against inflation and market volatility.',
      oneYearReturn: '15.1%',
      threeYearReturn: '8.4%',
      fiveYearReturn: '12.2%',
    },
    navHistory: navHistorySample.map(d => ({ ...d, nav: d.nav * 0.8 })),
    holdings: [
        { company: 'Gold Bullion', percentage: 99.5 },
        { company: 'Cash & Equivalents', percentage: 0.5 },
    ],
    performanceMetrics: [
      { metric: 'Alpha', value: '0.5%', average: '0.2%' },
      { metric: 'Beta', value: '0.1', average: '0.1' },
      { metric: 'Standard Deviation', value: '12.1%', average: '12.5%' },
      { metric: 'Sharpe Ratio', value: '0.6', average: '0.55' },
    ],
    peerComparison: [
        { fundName: 'Nippon India Gold Savings', peRatio: 'N/A', beta: 0.11, sharpeRatio: 0.58, upsideRatio: 102, downsideRatio: 98 },
        { fundName: 'SBI Gold Fund', peRatio: 'N/A', beta: 0.09, sharpeRatio: 0.61, upsideRatio: 100, downsideRatio: 100 },
    ],
    assetAllocation: [
      { name: 'Gold', value: 99, fill: 'var(--color-chart-2)' },
      { name: 'Cash', value: 1, fill: 'var(--color-chart-3)' },
    ],
    portfolioChanges: {
      sectorShifts: 'N/A as it is a single-commodity fund.',
      regulations: 'Adheres to SEBI guidelines for gold ETFs and gold funds.',
      exitLoad: '1% for redemption within 1 year.',
    },
    strategicPositioning: 'Offers a simple and efficient way to invest in gold, providing portfolio diversification.',
  },
  'parag-parikh-flexi-cap-fund': {
    name: 'Parag Parikh Flexi Cap Fund',
    slug: 'parag-parikh-flexi-cap-fund',
    aum: '₹66,182 Cr',
    manager: 'Rajeev Thakkar',
    investmentStrategy: {
      overview: 'A diversified equity scheme with a unique blend of domestic and international equities. The fund follows a value investing philosophy and is known for its low portfolio turnover.',
      oneYearReturn: '38.6%',
      threeYearReturn: '20.9%',
      fiveYearReturn: '23.8%',
    },
    navHistory: navHistorySample.map(d => ({ ...d, nav: d.nav * 1.5 })),
    holdings: [
      { company: 'HDFC Bank Ltd.', percentage: 7.9 },
      { company: 'Alphabet Inc. (Google)', percentage: 6.8 },
      { company: 'Bajaj Holdings & Investment Ltd.', percentage: 6.5 },
      { company: 'ITC Ltd.', percentage: 5.4 },
      { company: 'Microsoft Corporation', percentage: 5.2 },
    ],
    performanceMetrics: [
      { metric: 'Alpha', value: '7.5%', average: '3.1%' },
      { metric: 'Beta', value: '0.78', average: '0.95' },
      { metric: 'Standard Deviation', value: '15.2%', average: '18.0%' },
      { metric: 'Sharpe Ratio', value: '1.3', average: '0.9' },
    ],
    peerComparison: [
        { fundName: 'Quant Flexi Cap Fund', peRatio: '22.5', beta: 0.85, sharpeRatio: 1.4, upsideRatio: 120, downsideRatio: 80 },
        { fundName: 'HDFC Flexi Cap Fund', peRatio: '28.1', beta: 0.92, sharpeRatio: 1.0, upsideRatio: 95, downsideRatio: 90 },
    ],
    assetAllocation: [
      { name: 'Indian Equity', value: 70, fill: 'var(--color-chart-1)' },
      { name: 'Foreign Equity', value: 20, fill: 'var(--color-chart-4)' },
      { name: 'Debt', value: 8, fill: 'var(--color-chart-2)' },
      { name: 'Cash', value: 2, fill: 'var(--color-chart-3)' },
    ],
    portfolioChanges: {
      sectorShifts: 'Maintains a diversified portfolio with significant allocation to global tech giants. Recently increased stakes in domestic financial services.',
      regulations: 'Manages foreign allocation within SEBI prescribed limits.',
      exitLoad: '2% for redemption within 1 year, 1% for redemption between 1 and 2 years.',
    },
    strategicPositioning: 'Uniquely positioned with global diversification, offering a hedge against domestic market downturns and access to global tech growth.',
  },
  'quant-small-cap-fund': {
    name: 'Quant Small Cap Fund',
    slug: 'quant-small-cap-fund',
    aum: '₹21,243 Cr',
    manager: 'Ankit Pande',
    investmentStrategy: {
        overview: 'Follows a dynamic and aggressive investment style, frequently churning the portfolio to capitalize on market momentum. Focuses on identifying undervalued small-cap stocks with high growth potential.',
        oneYearReturn: '67.8%',
        threeYearReturn: '44.5%',
        fiveYearReturn: '48.9%',
    },
    navHistory: navHistorySample.map(d => ({ ...d, nav: d.nav * 2.1 })),
    holdings: [
        { company: 'Reliance Industries Ltd.', percentage: 9.5 },
        { company: 'Jio Financial Services Ltd.', percentage: 6.8 },
        { company: 'IRB Infrastructure Developers', percentage: 4.1 },
        { company: 'Adani Power Ltd.', percentage: 3.5 },
        { company: 'HDFC Bank Ltd.', percentage: 3.2 },
    ],
    performanceMetrics: [
        { metric: 'Alpha', value: '15.2%', average: '5.5%' },
        { metric: 'Beta', value: '0.88', average: '0.92' },
        { metric: 'Standard Deviation', value: '22.5%', average: '24.1%' },
        { metric: 'Sharpe Ratio', value: '1.9', average: '1.1' },
    ],
    peerComparison: [
        { fundName: 'Nippon India Small Cap', peRatio: '30.1', beta: 0.90, sharpeRatio: 1.5, upsideRatio: 110, downsideRatio: 95 },
        { fundName: 'SBI Small Cap Fund', peRatio: '32.4', beta: 0.85, sharpeRatio: 1.6, upsideRatio: 105, downsideRatio: 90 },
    ],
    assetAllocation: [
        { name: 'Equity', value: 96, fill: 'var(--color-chart-1)' },
        { name: 'Debt', value: 1, fill: 'var(--color-chart-2)' },
        { name: 'Cash', value: 3, fill: 'var(--color-chart-3)' },
    ],
    portfolioChanges: {
        sectorShifts: 'Highly dynamic. Recently increased allocation to infrastructure and energy sectors.',
        regulations: 'Adheres to SEBI norms for small-cap funds.',
        exitLoad: '1% for redemption within 1 year.',
    },
    strategicPositioning: 'Aims for high alpha through active, momentum-based trading. Suitable for investors with a very high risk appetite.',
  },
  'motilal-oswal-midcap-fund': {
    name: 'Motilal Oswal Midcap Fund',
    slug: 'motilal-oswal-midcap-fund',
    aum: '₹10,534 Cr',
    manager: 'Niket Shah',
    investmentStrategy: {
      overview: 'Focuses on mid-cap companies with strong growth potential and quality management. The fund aims to identify and invest in "Quality, Growth, Longevity & Price" (QGLP) stocks.',
      oneYearReturn: '55.2%',
      threeYearReturn: '33.1%',
      fiveYearReturn: '28.9%',
    },
    navHistory: navHistorySample.map(d => ({ ...d, nav: d.nav * 1.8 })),
    holdings: [
        { company: 'Tube Investments of India Ltd.', percentage: 6.2 },
        { company: 'Persistent Systems Ltd.', percentage: 5.8 },
        { company: 'IDFC First Bank Ltd.', percentage: 4.9 },
        { company: 'Deepak Nitrite Ltd.', percentage: 4.5 },
        { company: 'K.P.R. Mill Ltd.', percentage: 4.1 },
    ],
    performanceMetrics: [
        { metric: 'Alpha', value: '8.1%', average: '4.2%' },
        { metric: 'Beta', value: '0.85', average: '0.90' },
        { metric: 'Standard Deviation', value: '20.1%', average: '21.5%' },
        { metric: 'Sharpe Ratio', value: '1.6', average: '1.0' },
    ],
    peerComparison: [
        { fundName: 'HDFC Mid-Cap Opportunities', peRatio: '35.2', beta: 0.88, sharpeRatio: 1.4, upsideRatio: 102, downsideRatio: 92 },
        { fundName: 'Kotak Emerging Equity', peRatio: '38.1', beta: 0.86, sharpeRatio: 1.5, upsideRatio: 105, downsideRatio: 90 },
    ],
    assetAllocation: [
        { name: 'Equity', value: 94, fill: 'var(--color-chart-1)' },
        { name: 'Cash', value: 6, fill: 'var(--color-chart-3)' },
    ],
    portfolioChanges: {
        sectorShifts: 'Increased exposure to chemicals and engineering sectors while trimming some IT holdings.',
        regulations: 'Compliant with SEBI regulations for mid-cap funds.',
        exitLoad: '1% for redemption within 1 year.',
    },
    strategicPositioning: 'Focused on high-quality mid-cap companies with a long-term growth runway. Aims to balance growth and quality.',
  },
  'bandhan-small-cap-fund': {
    name: 'Bandhan Small Cap Fund',
    slug: 'bandhan-small-cap-fund',
    aum: '₹5,529 Cr',
    manager: 'Viraj Kulkarni',
    investmentStrategy: {
      overview: 'Aims for capital appreciation by investing in a diversified portfolio of small-cap stocks. The fund focuses on businesses with high growth potential, scalable business models, and a strong competitive edge.',
      oneYearReturn: '72.3%',
      threeYearReturn: '35.8%',
      fiveYearReturn: '31.2%',
    },
    navHistory: navHistorySample.map(d => ({ ...d, nav: d.nav * 2.3 })),
    holdings: [
        { company: 'Apar Industries Ltd.', percentage: 4.5 },
        { company: 'Cholamandalam Financial Holdings', percentage: 3.9 },
        { company: 'Century Plyboards (India) Ltd.', percentage: 3.5 },
        { company: 'RBL Bank Ltd.', percentage: 3.1 },
        { company: 'Greenpanel Industries Ltd.', percentage: 2.9 },
    ],
    performanceMetrics: [
        { metric: 'Alpha', value: '12.5%', average: '5.5%' },
        { metric: 'Beta', value: '0.91', average: '0.92' },
        { metric: 'Standard Deviation', value: '23.8%', average: '24.1%' },
        { metric: 'Sharpe Ratio', value: '1.7', average: '1.1' },
    ],
    peerComparison: [
        { fundName: 'Quant Small Cap Fund', peRatio: '22.5', beta: 0.88, sharpeRatio: 1.9, upsideRatio: 115, downsideRatio: 90 },
        { fundName: 'Nippon India Small Cap', peRatio: '30.1', beta: 0.90, sharpeRatio: 1.5, upsideRatio: 110, downsideRatio: 95 },
    ],
    assetAllocation: [
        { name: 'Equity', value: 95, fill: 'var(--color-chart-1)' },
        { name: 'Cash', value: 5, fill: 'var(--color-chart-3)' },
    ],
    portfolioChanges: {
        sectorShifts: 'Recently increased allocation to financial services and building materials sectors.',
        regulations: 'Adheres to SEBI norms for small-cap funds.',
        exitLoad: '1% for redemption within 1 year.',
    },
    strategicPositioning: 'Focuses on niche small-cap leaders with strong growth prospects, aiming to deliver high alpha for investors with a high risk appetite.',
  },
  'sbi-bluechip-fund': {
    name: 'SBI BlueChip Fund',
    slug: 'sbi-bluechip-fund',
    aum: '₹47,358 Cr',
    manager: 'Sohini Andani',
    investmentStrategy: {
      overview: 'A large-cap fund that invests in the top 100 companies by market capitalization, aiming for steady growth and wealth creation over the long term.',
      oneYearReturn: '25.5%',
      threeYearReturn: '14.8%',
      fiveYearReturn: '16.5%',
    },
    navHistory: navHistorySample.map(d => ({ ...d, nav: d.nav * 1.15 })),
    holdings: [
      { company: 'HDFC Bank Ltd.', percentage: 9.5 },
      { company: 'ICICI Bank Ltd.', percentage: 9.1 },
      { company: 'Reliance Industries Ltd.', percentage: 7.8 },
      { company: 'Infosys Ltd.', percentage: 6.2 },
      { company: 'Larsen & Toubro Ltd.', percentage: 4.9 },
    ],
    performanceMetrics: [
      { metric: 'Alpha', value: '1.8%', average: '1.5%' },
      { metric: 'Beta', value: '0.94', average: '1.0' },
      { metric: 'Standard Deviation', value: '18.2%', average: '19.2%' },
      { metric: 'Sharpe Ratio', value: '0.78', average: '0.7' },
    ],
    peerComparison: [
        { fundName: 'Nippon India Large Cap', peRatio: '27.2', beta: 0.95, sharpeRatio: 0.8, upsideRatio: 88, downsideRatio: 88 },
        { fundName: 'ICICI Pru Bluechip', peRatio: '27.5', beta: 0.96, sharpeRatio: 0.82, upsideRatio: 90, downsideRatio: 88 },
    ],
    assetAllocation: [
      { name: 'Equity', value: 94, fill: 'var(--color-chart-1)' },
      { name: 'Debt', value: 4, fill: 'var(--color-chart-2)' },
      { name: 'Cash', value: 2, fill: 'var(--color-chart-3)' },
    ],
    portfolioChanges: {
      sectorShifts: 'Maintains a stable allocation with a slight overweight on the banking and financial services sector.',
      regulations: 'Fully compliant with SEBI large-cap regulations.',
      exitLoad: '1% for redemption within 1 year.',
    },
    strategicPositioning: 'A core portfolio holding for investors seeking stable returns from blue-chip companies.',
  },
  'icici-prudential-bluechip-fund': {
    name: 'ICICI Prudential Bluechip Fund',
    slug: 'icici-prudential-bluechip-fund',
    aum: '₹55,459 Cr',
    manager: 'Anish Tawakley',
    investmentStrategy: {
      overview: 'Focuses on investing in large-cap stocks, with a bottom-up approach to stock selection. The fund aims for capital appreciation by investing in well-established companies.',
      oneYearReturn: '29.1%',
      threeYearReturn: '16.5%',
      fiveYearReturn: '18.2%',
    },
    navHistory: navHistorySample.map(d => ({ ...d, nav: d.nav * 1.25 })),
    holdings: [
      { company: 'ICICI Bank Ltd.', percentage: 10.2 },
      { company: 'Reliance Industries Ltd.', percentage: 8.9 },
      { company: 'HDFC Bank Ltd.', percentage: 8.5 },
      { company: 'Infosys Ltd.', percentage: 7.1 },
      { company: 'Larsen & Toubro Ltd.', percentage: 5.3 },
    ],
    performanceMetrics: [
      { metric: 'Alpha', value: '2.5%', average: '1.5%' },
      { metric: 'Beta', value: '0.96', average: '1.0' },
      { metric: 'Standard Deviation', value: '18.8%', average: '19.2%' },
      { metric: 'Sharpe Ratio', value: '0.82', average: '0.7' },
    ],
    peerComparison: [
      { fundName: 'SBI BlueChip Fund', peRatio: '25.9', beta: 0.94, sharpeRatio: 0.78, upsideRatio: 88, downsideRatio: 85 },
      { fundName: 'HDFC Top 100', peRatio: '26.1', beta: 0.98, sharpeRatio: 0.75, upsideRatio: 85, downsideRatio: 90 },
    ],
    assetAllocation: [
      { name: 'Equity', value: 93, fill: 'var(--color-chart-1)' },
      { name: 'Debt', value: 5, fill: 'var(--color-chart-2)' },
      { name: 'Cash', value: 2, fill: 'var(--color-chart-3)' },
    ],
    portfolioChanges: {
      sectorShifts: 'Overweight on private sector banks and energy. Underweight on consumer goods.',
      regulations: 'Strictly adheres to SEBI norms for large-cap funds.',
      exitLoad: '1% for redemption within 1 year.',
    },
    strategicPositioning: 'Aims to generate alpha through stock selection within the large-cap space. Suitable for long-term investors.',
  },
  'hdfc-mid-cap-opportunities-fund': {
    name: 'HDFC Mid-Cap Opportunities Fund',
    slug: 'hdfc-mid-cap-opportunities-fund',
    aum: '₹65,394 Cr',
    manager: 'Chirag Setalvad',
    investmentStrategy: {
      overview: 'One of the largest mid-cap funds, it invests in a diversified portfolio of mid-cap stocks with a focus on high-quality companies with sustainable growth prospects.',
      oneYearReturn: '48.9%',
      threeYearReturn: '28.5%',
      fiveYearReturn: '25.5%',
    },
    navHistory: navHistorySample.map(d => ({ ...d, nav: d.nav * 1.7 })),
    holdings: [
        { company: 'The Indian Hotels Company Ltd.', percentage: 4.5 },
        { company: 'Cholamandalam Investment and Finance', percentage: 4.1 },
        { company: 'Max Financial Services Ltd.', percentage: 3.8 },
        { company: 'Tata Communications Ltd.', percentage: 3.5 },
        { company: 'Apollo Tyres Ltd.', percentage: 3.2 },
    ],
    performanceMetrics: [
        { metric: 'Alpha', value: '6.5%', average: '4.2%' },
        { metric: 'Beta', value: '0.88', average: '0.90' },
        { metric: 'Standard Deviation', value: '20.5%', average: '21.5%' },
        { metric: 'Sharpe Ratio', value: '1.4', average: '1.0' },
    ],
    peerComparison: [
        { fundName: 'Kotak Emerging Equity', peRatio: '38.1', beta: 0.86, sharpeRatio: 1.5, upsideRatio: 105, downsideRatio: 90 },
        { fundName: 'Motilal Oswal Midcap Fund', peRatio: '32.1', beta: 0.85, sharpeRatio: 1.6, upsideRatio: 108, downsideRatio: 88 },
    ],
    assetAllocation: [
        { name: 'Equity', value: 92, fill: 'var(--color-chart-1)' },
        { name: 'Cash', value: 8, fill: 'var(--color-chart-3)' },
    ],
    portfolioChanges: {
        sectorShifts: 'Increased allocation in the hospitality and financial services sectors.',
        regulations: 'Compliant with SEBI mid-cap fund regulations.',
        exitLoad: '1% if redeemed within 1 year.',
    },
    strategicPositioning: 'Aims to identify and invest in the future blue-chips of the Indian market.',
  },
  'uti-nifty-50-index-fund': {
    name: 'UTI Nifty 50 Index Fund',
    slug: 'uti-nifty-50-index-fund',
    aum: '₹17,456 Cr',
    manager: 'Sharwan Kumar Goyal',
    investmentStrategy: {
      overview: 'A passive index fund that aims to replicate the performance of the Nifty 50 index. It offers exposure to the 50 largest companies in India at a low cost.',
      oneYearReturn: '24.5%',
      threeYearReturn: '14.1%',
      fiveYearReturn: '15.8%',
    },
    navHistory: navHistorySample.map(d => ({ ...d, nav: d.nav * 1.1 })),
    holdings: [
      { company: 'Reliance Industries Ltd.', percentage: 10.5 },
      { company: 'HDFC Bank Ltd.', percentage: 9.8 },
      { company: 'ICICI Bank Ltd.', percentage: 7.9 },
      { company: 'Infosys Ltd.', percentage: 6.5 },
      { company: 'Tata Consultancy Services Ltd.', percentage: 5.2 },
    ],
    performanceMetrics: [
      { metric: 'Tracking Error', value: '0.05%', average: '0.10%' },
      { metric: 'Beta', value: '1.0', average: '1.0' },
      { metric: 'Standard Deviation', value: '18.0%', average: '18.0%' },
      { metric: 'Sharpe Ratio', value: '0.7', average: '0.7' },
    ],
    peerComparison: [
        { fundName: 'HDFC Index Fund - Nifty 50 Plan', peRatio: '25.5', beta: 1.0, sharpeRatio: 0.7, upsideRatio: 100, downsideRatio: 100 },
        { fundName: 'ICICI Pru Nifty 50 Index Fund', peRatio: '25.5', beta: 1.0, sharpeRatio: 0.7, upsideRatio: 100, downsideRatio: 100 },
    ],
    assetAllocation: [
      { name: 'Equity', value: 99.8, fill: 'var(--color-chart-1)' },
      { name: 'Cash', value: 0.2, fill: 'var(--color-chart-3)' },
    ],
    portfolioChanges: {
      sectorShifts: 'Portfolio is rebalanced as per changes in the Nifty 50 index composition.',
      regulations: 'Follows SEBI guidelines for index funds.',
      exitLoad: 'No exit load.',
    },
    strategicPositioning: 'Ideal for investors looking for market-linked returns without stock selection risk. A low-cost core portfolio component.',
  },
  'icici-prudential-gilt-fund': {
    name: 'ICICI Prudential Gilt Fund',
    slug: 'icici-prudential-gilt-fund',
    aum: '₹7,123 Cr',
    manager: 'Anuj Tagra',
    investmentStrategy: {
      overview: 'Invests exclusively in government securities (G-Secs) of varying maturities. The fund manager actively manages the portfolio\'s duration based on interest rate forecasts.',
      oneYearReturn: '8.5%',
      threeYearReturn: '6.2%',
      fiveYearReturn: '7.8%',
    },
    navHistory: navHistorySample.map(d => ({ ...d, nav: d.nav * 0.9 })),
    holdings: [
      { company: 'Government of India Bond (2033)', percentage: 15.2 },
      { company: 'Government of India Bond (2028)', percentage: 12.8 },
      { company: 'Government of India Bond (2038)', percentage: 10.5 },
      { company: 'State Development Loans', percentage: 25.0 },
      { company: 'Treasury Bills', percentage: 5.5 },
    ],
    performanceMetrics: [
        { metric: 'Average Maturity', value: '8.2 years', average: '7.5 years' },
        { metric: 'Modified Duration', value: '5.5 years', average: '5.2 years' },
        { metric: 'Yield to Maturity', value: '7.1%', average: '7.0%' },
    ],
    peerComparison: [
        { fundName: 'SBI Magnum Gilt Fund', peRatio: 'N/A', beta: -0.2, sharpeRatio: 0.4, upsideRatio: 100, downsideRatio: 100 },
        { fundName: 'Kotak Gilt Investment', peRatio: 'N/A', beta: -0.22, sharpeRatio: 0.42, upsideRatio: 101, downsideRatio: 99 },
    ],
    assetAllocation: [
      { name: 'Bonds', value: 98, fill: 'var(--color-chart-5)' },
      { name: 'Cash', value: 2, fill: 'var(--color-chart-3)' },
    ],
    portfolioChanges: {
      sectorShifts: 'Recently increased duration to benefit from expected softening of interest rates.',
      regulations: 'Invests at least 80% in G-Secs as per SEBI regulations.',
      exitLoad: 'No exit load.',
    },
    strategicPositioning: 'Offers a safe investment option with no credit risk. Suitable for conservative investors seeking to benefit from interest rate movements.',
  },
  'embassy-office-parks-reit': {
    name: 'Embassy Office Parks REIT',
    slug: 'embassy-office-parks-reit',
    aum: '₹42,500 Cr (Market Cap)',
    manager: 'Embassy Group',
    investmentStrategy: {
      overview: 'Indias first listed REIT, it owns and operates a portfolio of high-quality office parks and commercial properties in major Indian cities. Aims to provide stable income distribution (dividends) and long-term capital appreciation.',
      oneYearReturn: '12.5% (Total Return)',
      threeYearReturn: '8.1% (p.a.)',
      fiveYearReturn: 'N/A (listed in 2019)',
    },
    navHistory: navHistorySample.map(d => ({ ...d, nav: d.nav * 1.05 })),
    holdings: [
        { company: 'Embassy Manyata Business Park, Bangalore', percentage: 35 },
        { company: 'Embassy TechVillage, Bangalore', percentage: 25 },
        { company: 'Embassy GolfLinks, Bangalore', percentage: 15 },
        { company: 'Embassy 247, Mumbai', percentage: 10 },
        { company: 'Other Properties', percentage: 15 },
    ],
    performanceMetrics: [
        { metric: 'Dividend Yield', value: '6.5%', average: '5.8%' },
        { metric: 'Loan to Value (LTV)', value: '28%', average: '35%' },
        { metric: 'Occupancy Rate', value: '88%', average: '85%' },
    ],
    peerComparison: [
        { fundName: 'Mindspace Business Parks REIT', peRatio: 'N/A', beta: 0.7, sharpeRatio: 0.5, upsideRatio: 105, downsideRatio: 95 },
        { fundName: 'Brookfield India REIT', peRatio: 'N/A', beta: 0.65, sharpeRatio: 0.45, upsideRatio: 102, downsideRatio: 98 },
    ],
    assetAllocation: [
      { name: 'REITs', value: 100, fill: 'var(--color-chart-4)' },
    ],
    portfolioChanges: {
      sectorShifts: 'Recently acquired a new Grade-A office asset in Chennai. Continuously focuses on maintaining high occupancy and rental collections.',
      regulations: 'Operates under SEBI (Real Estate Investment Trusts) Regulations, 2014.',
      exitLoad: 'No exit load on exchanges. Tax implications on capital gains apply.',
    },
    strategicPositioning: 'A market leader in the Indian office real estate sector, offering exposure to a portfolio of premium commercial assets with high-quality tenants.',
  },
  'brookfield-india-reit': {
    name: 'Brookfield India Real Estate Trust',
    slug: 'brookfield-india-reit',
    aum: '₹15,000 Cr (Market Cap)',
    manager: 'Brookfield Asset Management',
    investmentStrategy: {
      overview: 'Owns a portfolio of campus-format office parks in key gateway cities in India. The portfolio consists of properties that are institutionally managed and strategically located.',
      oneYearReturn: '10.2% (Total Return)',
      threeYearReturn: 'N/A (listed in 2021)',
      fiveYearReturn: 'N/A',
    },
    navHistory: navHistorySample.map(d => ({ ...d, nav: d.nav * 1.02 })),
    holdings: [
        { company: 'Kensington SEZ, Mumbai', percentage: 45 },
        { company: 'Candor TechSpace, Gurgaon', percentage: 25 },
        { company: 'Candor TechSpace, Kolkata', percentage: 20 },
        { company: 'Other Assets', percentage: 10 },
    ],
    performanceMetrics: [
        { metric: 'Dividend Yield', value: '7.1%', average: '5.8%' },
        { metric: 'Loan to Value (LTV)', value: '32%', average: '35%' },
        { metric: 'Occupancy Rate', value: '85%', average: '85%' },
    ],
    peerComparison: [
        { fundName: 'Embassy Office Parks REIT', peRatio: 'N/A', beta: 0.7, sharpeRatio: 0.5, upsideRatio: 105, downsideRatio: 95 },
        { fundName: 'Mindspace Business Parks REIT', peRatio: 'N/A', beta: 0.68, sharpeRatio: 0.48, upsideRatio: 103, downsideRatio: 97 },
    ],
    assetAllocation: [
      { name: 'REITs', value: 100, fill: 'var(--color-chart-4)' },
    ],
    portfolioChanges: {
      sectorShifts: 'Focused on leasing up vacant space and exploring acquisition opportunities for growth.',
      regulations: 'Complies with SEBI (Real Estate Investment Trusts) Regulations, 2014.',
      exitLoad: 'No exit load on exchanges. Capital gains tax is applicable.',
    },
    strategicPositioning: 'Backed by a global asset manager, it provides exposure to a quality portfolio of modern office parks with a focus on sustainable distributions.',
  },
  'aditya-birla-sun-life-corporate-bond-fund': {
    name: 'Aditya Birla Sun Life Corporate Bond Fund',
    slug: 'aditya-birla-sun-life-corporate-bond-fund',
    aum: '₹18,543 Cr',
    manager: 'Maneesh Dangi',
    investmentStrategy: {
      overview: 'Primarily invests in high-quality corporate bonds (AA+ and above rated). The fund aims to generate regular income and capital appreciation by investing in a portfolio of debt instruments of various maturities.',
      oneYearReturn: '7.8%',
      threeYearReturn: '6.5%',
      fiveYearReturn: '7.2%',
    },
    navHistory: navHistorySample.map(d => ({ ...d, nav: d.nav * 0.95 })),
    holdings: [
      { company: 'Reliance Industries Ltd. (Bond)', percentage: 8.5 },
      { company: 'HDFC Bank Ltd. (Bond)', percentage: 7.2 },
      { company: 'Power Finance Corporation Ltd. (Bond)', percentage: 6.8 },
      { company: 'National Highways Authority of India (Bond)', percentage: 5.5 },
      { company: 'Indian Railway Finance Corp (Bond)', percentage: 5.1 },
    ],
    performanceMetrics: [
        { metric: 'Average Maturity', value: '4.5 years', average: '4.0 years' },
        { metric: 'Modified Duration', value: '3.2 years', average: '3.0 years' },
        { metric: 'Yield to Maturity', value: '7.5%', average: '7.3%' },
    ],
    peerComparison: [
        { fundName: 'HDFC Corporate Bond Fund', peRatio: 'N/A', beta: -0.1, sharpeRatio: 0.8, upsideRatio: 102, downsideRatio: 98 },
        { fundName: 'ICICI Prudential Corporate Bond Fund', peRatio: 'N/A', beta: -0.12, sharpeRatio: 0.85, upsideRatio: 103, downsideRatio: 97 },
    ],
    assetAllocation: [
      { name: 'Bonds', value: 95, fill: 'var(--color-chart-5)' },
      { name: 'Cash', value: 5, fill: 'var(--color-chart-3)' },
    ],
    portfolioChanges: {
      sectorShifts: 'Maintaining a high-quality portfolio with a focus on stable public sector and top-tier private sector companies.',
      regulations: 'Invests at least 80% of its assets in corporate bonds with AA+ and above ratings.',
      exitLoad: 'No exit load.',
    },
    strategicPositioning: 'A relatively safe debt fund that is suitable for investors looking for stable income and lower volatility compared to equity funds.',
  },
  'motilal-oswal-sp-500-index-fund': {
    name: 'Motilal Oswal S&P 500 Index Fund',
    slug: 'motilal-oswal-sp-500-index-fund',
    aum: '₹5,678 Cr',
    manager: 'Ankush Sood',
    investmentStrategy: {
      overview: 'A passive fund that replicates the S&P 500 index, one of the most widely recognized benchmarks for US large-cap equities. It provides Indian investors with exposure to the US stock market.',
      oneYearReturn: '26.5%',
      threeYearReturn: '15.1%',
      fiveYearReturn: '18.5%',
    },
    navHistory: navHistorySample.map(d => ({ ...d, nav: d.nav * 1.3 })),
    holdings: [
      { company: 'Microsoft Corp.', percentage: 7.1 },
      { company: 'Apple Inc.', percentage: 6.5 },
      { company: 'NVIDIA Corp.', percentage: 5.8 },
      { company: 'Amazon.com, Inc.', percentage: 3.9 },
      { company: 'Meta Platforms, Inc.', percentage: 2.5 },
    ],
    performanceMetrics: [
        { metric: 'Tracking Error', value: '0.12%', average: '0.20%' },
        { metric: 'Beta (vs S&P 500)', value: '1.0', average: '1.0' },
        { metric: 'Standard Deviation', value: '20.5%', average: '20.0%' },
    ],
    peerComparison: [
        { fundName: 'Franklin India Feeder - US Opp', peRatio: '28.5', beta: 1.05, sharpeRatio: 0.9, upsideRatio: 110, downsideRatio: 90 },
        { fundName: 'DSP US Flexible Equity Fund', peRatio: '27.9', beta: 1.02, sharpeRatio: 0.85, upsideRatio: 108, downsideRatio: 92 },
    ],
    assetAllocation: [
      { name: 'Foreign Equity', value: 99, fill: 'var(--color-chart-4)' },
      { name: 'Cash', value: 1, fill: 'var(--color-chart-3)' },
    ],
    portfolioChanges: {
      sectorShifts: 'The portfolio is adjusted according to the weightage changes in the S&P 500 index.',
      regulations: 'Adheres to SEBI regulations for international funds.',
      exitLoad: '1% for redemption within 3 months.',
    },
    strategicPositioning: 'Offers a low-cost, passive way to diversify a portfolio by investing in the 500 largest publicly traded companies in the United States.',
  },
};
